version: '3'

services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./component:/app/component
      - ./public:/app/public
      - ./styles:/app/styles