import { UserProvider } from "../context";

import Head from "next/head";

import "antd/dist/antd.css";

function MyApp({ Component, pageProps }) {
  return (
    <UserProvider>
      <Head>
        <title>TODO APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  {console.log("APP")}
      <Component {...pageProps} />
    </UserProvider>
  );
}
export default MyApp;
