
import { useState } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Todo from "../component/todo";
import Head from "next/head";
export default function Home() {
  const [todos, setTodos] = useState('');
  const [todoList,setTodoslist]=useState([]);
  const addTodo = (e) => {
    e.preventDefault();
    console.log("todos",todos)
    setTodoslist(current => [...current, todos]);
   
    console.log(todoList);
    setTodos("");
  };
  return (
    <div className={styles.container}>
    {/* <Head>
        <title>TODO APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          TODO<a href="#">App</a>
        </h1>

        <div className={styles.grid}>
          {/* <form onSubmit={addTodo}> */}
            <div className={styles.card}>
              <input
                className={styles.input}
                type="text"
               
                onChange={(e) => setTodos(e.target.value)}
                value={todos}
                placeholder="Add items.."
              />
              <input 
              type="submit" 
              className={styles.button} 
              title="Add Todo" 
              onClick={addTodo}
              />
            </div>
          {/* </form> */}
        {todoList ? 
        (
           <Todo todos={todoList} addTodo={addTodo} />)
           :
           (<p>no todo item</p>)}
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
}
